### ISSUE TITLE
Web site icon

### ISSUE THREAD

**Issue by Justxd22** [Justxd22/ChillPill#6]
- take @0x3mr icon design
- Upload to github to `app/favicon.ico` folder
- Verfiy when loading the app the icon is displayed in tab bar like:    
![image](https://github.com/Justxd22/ChillPill/assets/66136622/a4206344-29c2-4572-ad32-d8e86e36d9fa)

**Comment by Justxd22** [comment]
- also add it to readme

**Comment by 0x3mr** [comment]
Done.
![image](https://github.com/Justxd22/ChillPill/assets/134318070/bda56708-6b64-4084-be26-a87e6aaab877)
